version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mcp-server/mosquitto/config:/mosquitto/config:ro
      - ./mcp-server/mosquitto/data:/mosquitto/data
      - ./mcp-server/mosquitto/log:/mosquitto/log

  mcp-server:
    build: ./mcp-server
    container_name: mcp-server
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mosquitto
    restart: unless-stopped
